### ISSUE TITLE
Super bug in undergraduateDegreeObtainedBystudent of cache server

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/LinGBM-OptimizationTechniquesExperiments#2]
In addition to all the problems described in #1, the resolver for undergraduateDegreeObtainedBystudent in the cache-variation of the test server has another, even worse problem: The if-block for the filter condition creates a new variable called `students` by using the keyword `let` (see [line 272](https://github.com/LiUGraphQL/LinGBM-OptimizationTechniquesExperiments/blob/64fd05f05e5b9ec97e8a8befead7d2e258c8c3ce/src/cache/resolver/resolver.js#L272)), which makes this new variable **not** visible outside of this block!!! Consequently, after doing all of the filtering, the resolver completely ignores what it just did and, instead, returns the unfiltered list of grad students (see line 310)!!!!  

Argh!!!

**Comment by chengsijin0817** [comment]
This issue is fixed in the latest commit (7fedcf7).

**Comment by hartig** [comment]
Thanks!
